# Generated by Django 4.1 on 2024-10-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária em Horas')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='controleDiscente.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LimiteFaltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_maxima', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Percentual Máximo de Faltas')),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_faltas', to='controleDiscente.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Faltas')),
                ('total_aulas', models.PositiveIntegerField(default=0, verbose_name='Total de Aulas')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='controleDiscente.matricula')),
            ],
        ),
    ]
